openapi: 3.2.0
info:
  title: OwnLocal Categories API
  version: v1
tags:
- name: Categories
paths:
  /api/v1/categories:
    get:
      summary: Retrieve a list of categories
      tags:
      - Categories
      security:
      - apiKey: []
      parameters:
      - name: sortedBy
        in: query
        example: createdAt,updatedAt,startDate,endDate
        schema:
          type: string
      - name: page
        in: query
        example: 2
        schema:
          type: integer
          format: int64
      - name: size
        in: query
        example: 20
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: categories found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/category'
      operationId: getApiV1Categories
      x-operation-id-source: derived
components:
  schemas:
    category:
      type: object
      properties:
        title:
          type: string
          example: Communication
        subCategories:
          type: array
          items:
            type: string
          example:
          - Broadcasting Services
          - Cable TV
          - Newspapers and Magazines
          - Other
          - Publishing
          - Radio Stations
          - Telecommunications
          - TV Stations
  securitySchemes:
    apiKey:
      type: apiKey
      name: Authorization
      in: header
